apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-trigger-binding
spec:
  params:
  - name: REPO_URL
    value: $(body.repository.clone_url)
  - name: REVISION
    value: $(body.pull_request.head.sha)
  - name: IMAGE
    value: madhan1115/go-sample-app:2020.08.30-15.34.02
