apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
namespace: dev
images:
  - name: madhan1115/go-sample-app # used for Kustomize matching
    newTag:
namePrefix: dev-
